name: Release for tags
on:
  push:
  pull_request:
  create:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json')
            }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install --dev
      - name: Build Electron
        run: npm run package-linux
      - name: Upload electron-linux
        uses: actions/upload-artifact@v4
        with:
          path: dist/linux-unpacked
          name: teslaterm-linux
  build-windows:
    name: Build on Windows
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: NPM install
        run: npm install --dev
      - name: Build Electron
        run: npm run package-windows
      - name: Upload electron-windows
        uses: actions/upload-artifact@v4
        with:
          path: dist/win-unpacked
          name: teslaterm-windows
  create-release:
    name: Create release if required
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    env:
      release: ${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')}}
    steps:
      - name: Download teslaterm-windows
        uses: actions/download-artifact@v4
        with:
          name: teslaterm-windows
          path: windows
      - name: Re-zip Windows artifact
        working-directory: windows
        run: zip -r ../teslaterm-windows.zip *
      - name: Download teslaterm-linux
        uses: actions/download-artifact@v4
        with:
          name: teslaterm-linux
          path: linux
      - name: Re-zip Linux artifact
        working-directory: linux
        run: zip -r ../teslaterm-linux.zip *
      - name: Create and upload release builds
        uses: softprops/action-gh-release@v1
        if: env.release == 'true'
        with:
          files: |
            teslaterm-linux.zip
            teslaterm-windows.zip
